### ISSUE TITLE
po2php fill untranslated units with template units

### ISSUE THREAD

**Issue by pc-jedi** [translate/translate#3366]
en.php
```php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Imprint',
'contact'=>'Contact',
);
```
Creating `template.pot` and create a copy of it:
```bash
php2po -P en.php template.pot
cp template.pot de.po
```

Filled `de.po` with ONE german translation:
```po
#. extracted from en.php
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-03 09:20+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 1.13.0\n"

#: $lang->'login'
msgid "Login"
msgstr ""

#: $lang->'imprint'
msgid "Imprint"
msgstr "Impressum"

#: $lang->'contact'
msgid "Contakt"
msgstr ""
```

Convert `de.po` to `de.php` with `en.php` as template:
```bash
po2php -t en.php de.po de.php
```

Result `de.php`:
```php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Impressum',
'contact'=>'Contakt',
);
```

Would it not be better to skip the units with empty `msgstr`? So that the result would look like:
```php
<?php
$lang = array(
'imprint'=>'Impressum',
);
```

**Comment by unho** [comment]
Given the original PHP file the translated PHP should be:

Result `de.php`:
```php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Impressum',
'contact'=>'Contact',
);
```

The reason why all the units are included in the final result, even if they are not translated or fuzzy, is that otherwise the program using this PHP file might break because of missing keys. Since the translation is actually done on the PO file having mixed languages in the output PHP is no problem.

Closing this.
