### ISSUE TITLE
PO to XLIFF conversion issue

### ISSUE THREAD

**Issue by darani73** [translate/translate#3458]
```xliff
<trans-unit id="email_access@$@You need to really know your subject and your members’ viewpoints. Then if somebody goes off in a different direction, you can finesse it and bring it back.">
        <source xml:lang="en-US">You need to really know your subject and your members’ viewpoints. Then if somebody goes off in a different direction, you can finesse it and bring it back.</source>
      </trans-unit>
````

The above translation is converted from xliff po but when converting to xliff i am getting error.
I am using python 3.5.1  and translate 1.9 i am using windows 10 OS so I didnot find any other higher version with windows installation kit. please how to solve this. I have attached screen of error.

```po
#: email_access%40%24%40You+need+to+really+know+your+subject+and+your+members%E2%80%99+viewpoints.+Then+if+somebody+goes+off+in+a+different+direction%2C+you+can+finesse+it+and+bring+it+back.
msgid ""
"You need to really know your subject and your members’ viewpoints. Then if "
"somebody goes off in a different direction, you can finesse it and bring it "
"back."
msgstr ""
```

![error](https://cloud.githubusercontent.com/assets/20199664/16441159/b1d73cde-3de5-11e6-862e-1f1c4573923a.png)

**Comment by dwaynebailey** [comment]
@darani73 are you able to paste the whole source.  I'd like to ensure that you actually have the correct encoding set for both the PO file, as it looks like it's using the default encoding but then finding something in another encoding.  Check the PO header or paste it here for us, please.

**Comment by darani73** [comment]
**I have attached my xliff file and PO file which i have generated by using xliff2po command
I have added extension as txt for the attached files because I am unable to upload xlf,PO extension files

I have run python -c "import sys; print(sys.getdefaultencoding())" in command prompt and i got utf-8**

[english.po.txt](https://github.com/translate/translate/files/338896/english.po.txt)
[English.xlf.txt](https://github.com/translate/translate/files/338897/English.xlf.txt)

**Comment by dwaynebailey** [comment]
Actually my bad.

Translate Toolkit 1.9 does not support Python 3, it only support Python 2.7.  We only introduced Python 3 support in the 2.0.0 version see https://github.com/translate/translate/releases/tag/2.0.0b2

The conversion happens fine for me using Translate Toolkit master `po2xliff english.po bob.xlf`.  Note though that the PO file contains many duplicate entries, so I'd expect possible failures at some other point in your roundtrip

**Comment by darani73** [comment]
I am unable to install 2.0.0. please tell me where i can download windows installation setup. 
or
how can i install this setup in windows 10

**Comment by dwaynebailey** [comment]
@darani73 validated with Translate Toolkit 1.9.0, and anything newer than that doesn't have that issue.

We haven't been able to make a Windows build since 1.9.0, we're still working on getting that back.  For now you can use a virtualenv, this does require a higher level of Windows proficiency

* [Install virtualenv and other things](http://www.tylerbutler.com/2012/05/how-to-install-python-pip-and-virtualenv-on-windows-with-powershell/)
* Once in your virtualenv
* `pip install translate-toolkit`
* `po2xliff --version` to double check you have the right version

**Comment by unho** [comment]
@darani73 I strongly suggest you to use latest Python 2.7 (or at least newer than Python 2.7.9) since it comes with `pip` tool bundled. This will strongly simplify installation of Translate Toolkit using a virtualenv. I also suggest you use `virtualenvwrapper-win` https://pypi.python.org/pypi/virtualenvwrapper-win to simplify handling of virtualenvs. So the following should work (tested on Windows 7):

- Install latest Python 2.7 (or newer than Python 2.7.9)
- Open `cmd.exe` or alike
- `pip install virtualenvwrapper-win`
- `mkvirtualenv ttk` being "ttk" the name for the new virtualenv
- `pip install translate-toolkit` to install latest stable or `pip install "translate-toolkit==2.0.0b1` to try latest beta
- `pip install "lxml>=3.0"` in order to be able to use XLIFF or other XML formats
- `po2xliff --version` to double check you have the right version

Next times you need to use Translate Toolkit just remember to:

- `workon ttk` to enable the virtualenv again
- Run the Translate Toolkit commands you want

**Comment by darani73** [comment]
thanks a lot 
It works fine

**Comment by dwaynebailey** [comment]
Marking this as solved, the underlying issue is fixed in newer versions of ttk.  The installation issues are a separate issue.

**Comment by dwaynebailey** [comment]
@darani73 we've added the above [Windows install instructions](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/installation.html#installing-on-windows) so hopefully we help future version of yourself.

**Comment by darani73** [comment]
AS per your instructions,I have installed and it is working in my machine in a web application.
but the same above  steps i followed in another machine. po2xliff is not working in the same web application It is creating a empty file. I don't what i am missing in that machine (both machines are running windows 10 OS) please help me to fix the issue
