### ISSUE TITLE
Yml files are not parsed

### ISSUE THREAD

**Issue by tadejstanic** [translate/translate#3518]
I've installed the docker version of this excellent app but can't make it to parse the yml files.

In webplate container I've checked what version of translation-toolkit am I using and got the latest one. 

```
weblate@549a7ccd02af:/$ prop2po --version
prop2po 2.0.0b7
```
I did notice this in the docs: 

> You currently need patched version of translate-toolkit to support YAML. Check translate-toolkit issue tracker for more details.

but I think this instruction is somehow obsolete regarding that I'm using the latest version of the toolkit. Or am I missing something...

Here is also a screenshot from the admin panel to see the error:

![yaml-error](https://cloud.githubusercontent.com/assets/7260332/20170882/5fafd328-a72e-11e6-99c4-72cc9f411f10.png)

In the dropdown for choosing a file format, the `yml` option is also missing.

**Comment by unho** [comment]
Translate Toolkit 2.0.0b7 includes support for reading YAML files. I don't know what you are talking about docker version and what that screenshot is about, but I guess it is Weblate. If that is the case I suggest you to contact Weblate developers first in order to ensure the problem is actually on Translate Toolkit.

I will leave this issue open until we get extra information.

**Comment by tadejstanic** [comment]
Thx Leandro. Obviously wrong place. My fault.

**Comment by unho** [comment]
No problem. I hope it gets fixed soon for your convenience.
