### ISSUE TITLE
Adding support to prepend and override note in addnotes for propunit and AndroidResourceUnit

### ISSUE THREAD

**Issue by Dchau95** [translate/translate#3677]
Hi, I noticed in the source code that the `addnotes` method in `propunit` and `AndroidResourceUnit` does not support prepending and replacing/overriding notes/comments. Is there any plans or possibility to do this support? I apologize if there exists a reported issue before, I could not find anything related.

Edit: I doubled checked and noticed there is a `removenotes()` method, so I think that sorts the issues of replacing/overriding notes.

**Comment by unho** [comment]
What you ask for is already supported by:

- Reading existing comments
- Remove them all from the unit
- Add the new comments you want (either prepending some comment or replacing/overwriting any of the previously existing)

We don't have plans to add any custom code to support any of these workflows since current code already allows to achieve the results you want.
