### ISSUE TITLE
html2po incorrectly strips html

### ISSUE THREAD

**Issue by deAtog** [translate/translate#3768]
Given a block element that contains inline html, e.g. a paragraph containing links, html2 po will incorrectly strip the inline html in some cases: E.g:

```html
<p><a href="http://example.com">This is a link</a> but this is not. <a href="http://example.com">However this is too</a></p>
```

Will be transformed into the following string for translating:

`This is a link</a> but this is not. <a href="http://example.com">However this is too`

From the comments in the code, it appears this functionality was included to strip out what the author considered to be unnecessary html in the translation text. The regular expression used for this is unable to accurately determine which end tag matches the start tag.

Since html2po does not support the insertion of placeholders, the only solution here is to leave the inline html intact regardless of how unnecessary it may be for a translator.

**Comment by anderskaplan** [comment]
Can you please explain what your use case is, i.e., why doesn't it work for you to have the leading and trailing tags removed?

**Comment by ngrilly** [comment]
Because it makes difficult using html2po to extract strings to be translated and then po2html to replace the untranslated strings by the translated strings. In some languages, the order of words can be different from English, which means the <a>...</a> is moved in a different position in the sentence. With the opening or the closing tag missing, it's not possible to move it.
