### ISSUE TITLE
[html2po] translate language version in <html lang="en">

### ISSUE THREAD

**Issue by fabianegli** [translate/translate#3884]
The `lang` attribute form the html tag is not extracted for translation - I think it is obvious that it should be.

**Comment by anderskaplan** [comment]
I'd be happy to provide a pull request for this change, but I'd like to get the maintainers' opinon on it first. The reason is that there is a unit test to check that the lang tag is *not* extracted for translation. (test_html2po.py line 60)

The decription of the test says "test to ensure that we no longer use the lang attribure" (sic), but does not give any hints to the reason for it.

I have a use case where I want to translate static html pages. It would be useful to swap out the lang attribute at the same time as swapping out the translated content.
