### ISSUE TITLE
po2php fills translation files with source values rather than translations

### ISSUE THREAD

**Issue by redalpha01** [translate/translate#3909]
Version 2.4.0

Hello, 

I have two translation folders (en and fr) with files following this structure:
```
<?php return [
	'key'    => 'value',
	'key2'       => 'value2',
];
```
When I do 

> php2po -P lang/en pot/ 

and 

> php2po -t lang/en lang/fr po-fr/

I get my pot and my po files where the English values are correctly translated to French.

However, when I do 

> po2php - t lang/en po-fr/ lang/fr 
it replaces the french values in the french translation files with the english source values.

Any idea what I'm doing wrong?

**Comment by unho** [comment]
@redalpha01 Can you please share some of those files to replicate the error?

**Comment by haugli92** [comment]
I do experience the same issue. Anyone know why this happens or is it a bug?

**Comment by nijel** [comment]
I've quickly looked at this and it seems that po2php is duplicating the PHP parser, and it behaves slightly differently than when extracting the strings with php2po. Because of this it doesn't match strings in some cases and uses source instead of the translation because of this. It should be really rewritten to use the same parser as translate.storage.php...

**Comment by haugli92** [comment]
Could this be fixed pretty soon? I'll gladly donate 10$ if this fixes the issue :)

**Comment by nijel** [comment]
Switching it to use the other parser is done in https://github.com/translate/translate/pull/4271, whether it can be considered a complete fix is yet to be decided (it removes some features previously present).

**Comment by haugli92** [comment]
Seems to be working fine now.
