### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nijel** [translate/translate#3966]
@unho what about releasing soon? 2.5.1?

I recently see many people being hit by https://github.com/translate/translate/pull/3951 and https://github.com/translate/translate/issues/3939 is annoying on Python 3.8.

There are other fixes in master as well, see https://github.com/translate/translate/compare/2.5.0...master

**Comment by julen** [comment]
@nijel don't you have release rights on PyPI yet? I don't see any reason why you shouldn't at this point. I reckon @unho or @dwaynebailey should be able to give them to you.

**Comment by unho** [comment]
I just gave permissions on PyPI to @nijel but I would need his username on ReadTheDocs to provide permissions there as well.

Instructions on how to release are detailed (I don't strictly follow all of the steps) in http://docs.translatehouse.org/projects/translate-toolkit/en/latest/developers/releasing.html

**Comment by unho** [comment]
@nijel Maybe you want to try and see if you can do the release yourself. I can take care of the ReadTheDocs step, but it would be great if you pass me your ReadTheDocs username so I can give you permissions.

**Comment by nijel** [comment]
I'm `nijel` on ReadTheDocs as well.

The release process looks like many manual steps, what about automating some parts of that?

* The tests should be done in the CI, there should be no need to do manual testing.
* Releases can be scripted and GitHub release notes can probably reuse text from the docs (this is how I do that for Weblate: https://github.com/WeblateOrg/weblate/blob/master/scripts/create-release, and docs: https://docs.weblate.org/en/latest/contributing.html#releasing-weblate)
* All of that probably could be done on pushing the Git tag (for example this is what I use for translation-finder: https://github.com/WeblateOrg/translation-finder/blob/master/.github/workflows/setup.yml)

**Comment by unho** [comment]
@nijel I've just added you as maintainer in ReadTheDocs.

Yes, release involves a lot of manual steps.

* Tests outlined in release instructions are for testing the actual package for the release. I don't see how that can be automated in CI.
* Release notes for Translate Toolkit might get complicated, so in order to not over-complicate the list of releases in GitHub we just outline the largest two or three changes and then publish a link to the full release notes as you can see in https://github.com/translate/translate/releases. If you find a way to automate that I am open to check.

Anyway I would first go for you to follow current instructions to verify you can perform the release.

**Comment by unho** [comment]
@nijel BTW, I suggest you create a PR so changes for the new release can be reviewed, and to also ensure CI stills works after upgrading requirements (something that sometimes tends to break tests).

**Comment by nijel** [comment]
I've automated some manual checks in https://github.com/translate/translate/pull/3967, see https://github.com/translate/translate/runs/576324085?check_suite_focus=true for results.

**Comment by nijel** [comment]
Released. I hope I didn't mess up anything :-).

[Announce the world](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/developers/releasing.html#announce-to-the-world) seems outdated - the mailing lists are no longer existing? Is IRC still in use? Is there Pootle channel on Gitter? Basically I've skipped everything from there besides Wikipedia and Twitter.

**Comment by unho** [comment]
Regarding announcing:
* I no longer usually announce on mailing lists,
* I not always update gitter channel status message, but I usually post there a link to the tweet,
* IRC was dropped in favor of gitter, but the channel was never formally closed, but it has been years since I last entered there,
* Email important users was a business related step for Translate House, which no longer exists,
* I always tweet,
* I always update Wikipedia page.

I am going to quickly check release is correct.

**Comment by unho** [comment]
@nijel I see that sublists seem to be on indented blocks http://docs.translatehouse.org/projects/translate-toolkit/en/latest/releases/2.5.1.html 

I would also post the tweet on Gitter, so people are aware (there are distro packagers following releases there). That would also allow people there to retweet.

Everything else looks ok
