### ISSUE TITLE
Regression with properties files introduced after 2.3.0

### ISSUE THREAD

**Issue by jordimas** [translate/translate#4402]
With translate-toolkit 2.3.0 the following use to work:

* I have attached the ca.strings (input) and en.strings (template) [files.zip](https://github.com/translate/translate/files/6907711/files.zip)
* Running `prop2po -t en.strings -i ca.strings -o ca.po --personality=strings --encoding=utf-8` converted to a valid and good PO file (see ca-old.po in the zip file)

Now with translate-toolkit 3.3.4 the PO file generated using the same input files & script (see ca.po in the zip file) is completely broken. 

A regression after translate-toolkit 2.3.0 was introduced.

Let me know if you need any other detail

**Comment by nijel** [comment]
Well, you use Apple strings parser and the format has entries terminated by a semicolon (see https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/MaintaingYourOwnStringsFiles/MaintaingYourOwnStringsFiles.html). 

So, it was a bug that it worked before, and it was fixed by 237ac6d237774ce2a6c74e0f836ef5bee7bb8d76, see https://github.com/translate/translate/pull/3825.

You most likely want to use a different personality or format.

**Comment by jordimas** [comment]
Makes sense, thanks!
