### ISSUE TITLE
Translate Toolkit should expose attributes in Fluent's storages

### ISSUE THREAD

**Issue by pan93412** [translate/translate#4649]
Related: https://github.com/WeblateOrg/weblate/issues/7742#issuecomment-1147283794

**Comment by nijel** [comment]
To clarify - the attributes are now exposed as a dictionary:

https://github.com/translate/translate/blob/650b3d28d8a739beef827e0261dc409e4add799c/translate/storage/fluent.py#L93-L94

This way it really doesn't fit into way translatable strings are exposed. Each attribute should become a separate `Unit` and some folding when serializing will be needed.

**Comment by emmapeel2** [comment]
We want to move Tor Browser localization to Fluent, but we also have problems to load this file: https://gitlab.torproject.org/tpo/translation/-/blob/basebrowser-newidentityftl/en-US/new-identity.ftl

**Comment by nijel** [comment]
I currently do not have any plans on this.

**Comment by henry-torproject** [comment]
> Each attribute should become a separate `Unit` and some folding when serializing will be needed.

@nijel would it be possible to keep the attributes grouped together within the same unit, rather than split attributes into separate units? Or split them, but still associate them somehow?

Ideally, weblate's interface would be able to show the attributes grouped together along with their attribute names, because they can provide important context to each other. Similar to how  pontoon handles it https://pontoon.mozilla.org/es-ES/firefox/browser/browser/aboutDialog.ftl/?string=192297

I guess weblate has something similar set up for handling plurals, which it groups together in the same page.

**Comment by nijel** [comment]
There is nothing in Weblate that would fit this. Looking at the example posted in https://github.com/WeblateOrg/weblate/issues/7742#issue-1261056973 I really think the best approach is to translate each string separately. These are really independent strings and should be handled that way in Weblate.

**Comment by henry-torproject** [comment]
> There is nothing in Weblate that would fit this.

How much work would it take to enable this? Would it be a matter of a few tweaks, or is it outside of weblate's current structure?

> Looking at the example posted in [WeblateOrg/weblate#7742 (comment)](https://github.com/WeblateOrg/weblate/issues/7742#issue-1261056973) I really think the best approach is to translate each string separately. These are really independent strings and should be handled that way in Weblate.

When fluent is used in a HTML context the attributes correspond to the HTML attributes. So the strings are related in that they correspond to the same HTML element. E.g.

```
my-button = Open File
  .accesskey = F
  .title = Choose a file from your computer
```

In this case the attributes are related to the text content. Especially "accesskey" is set based on the text content.

There would be ways to get around this with comments that would direct translators on how individual strings are related. However, it would be nice to be able to present the strings in this way since this is one of Fluent's strengths and main features in a HTML context.

**Comment by nijel** [comment]
The strings still should be stored as separate units as this is needed for many Weblate features. Things like suggestions or checks should work on string level, not on the whole group.

We already have [Variants](https://docs.weblate.org/en/latest/devel/translations.html#variants) to group related strings, maybe it could be used here as well...

**Comment by henry-torproject** [comment]
We already have [Variants](https://docs.weblate.org/en/latest/devel/translations.html#variants) to group related strings, maybe it could be used here as well...

Thank you. I'll look into that as an option.

**Comment by henry-torproject** [comment]
@nijel ok, I will see if I can put together a patch to implement this. I'll read your contributing docs and try at the beginning of next year, so I might ask some more questions in the translate dev chat around then.
