### ISSUE TITLE
Do not include "Explanation" field in iOS strings files

### ISSUE THREAD

**Issue by tipa** [translate/translate#5121]
This is the same issue as posted in the weblate repo [here](https://github.com/WeblateOrg/weblate/issues/10290)

### Describe the issue

When downloading iOS strings, the "Explanations" are also exported, but not commented out:

```
Initial greeting.
"welcome1" = "Willkommen!";
Second greeting.
"welcome2" = "Guten Tag!";
```

However it should looks something like this:
```
/* Initial greeting. */
"welcome1" = "Willkommen!";

/* Second greeting. */
"welcome2" = "Guten Tag!";
```
https://developer.apple.com/documentation/swift-playgrounds/localizing-code-comments-and-string-literals#Create-a-Localization-Strings-File

This error shows up when launching an iOS/macOS app when using the exported strings file:
` Localizable: Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character " at line 1" UserInfo={NSDebugDescription=Unexpected character " at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Expected ';' or '=' after key at line 149" UserInfo={NSDebugDescription=Expected ';' or '=' after key at line 149}}
`

### Steps to reproduce the behavior

1. Add "Explanation" to String in Weblate
2. Download "iOS Strings" via API
3. Inspect strings file

### Expected behavior

Explanations aren't exported or properly commented out.
I would prefer that explanations aren't exported at all. They also aren't exported when downloading Android Strings files or .resw files (which is my source file format).

**Comment by nijel** [comment]
The root cause here is that comments are parsed including `/* */` or `//` and the serializer then uses them as they are without any checking:

https://github.com/translate/translate/blob/be742cef4ed34927d67d62eac6d115c1b9b5c34f/translate/storage/properties.py#L900-L904

Weblate adds them as a plain string and so they end up the file.

There are two possible solutions:

* Make serializer look at the content and add `//` at the beginning if needed.
* Make the parser parse the content of the comments and let the serializer add comment marks always.

The first approach doesn't change current behavior, the second one makes the format behave like others in the translate-toolkit.

**Comment by tipa** [comment]
The comments are not commented out (using line comments instead of block comments but they seem to work as well). However, the comments are still exported, while they aren't for Android XML or .resw files. Is there any way to disable export of comments for .string files?
